hora = float(input('Quanto você ganha por hora: '))
nhoras = int(input('Quantas horas você trabalha por mês: '))
salario = (hora * nhoras)
print('Salário bruto:')
print('R$:',salario)
inss = (salario * 0.08)
print('Quantia paga ao INSS:')
print('R$:',inss)
sindicato = (salario * 0.05)
print('Quantia paga ao sindicato:')
print('R$:',sindicato)
liquido = salario - (salario * 0.24)
print('Salário líquido:')
print('R$:',liquido)
