nome = input("digite nome: ")
endereco = input("digite endereço: ")
bairro = input("digite bairro: ")
cidade = input("digite cidade: ")
estado = input("digite estado: ")
telefone = int(input("digite telefone: "))
print ("nome: ",nome)
print ("endereço: ",endereco)
print ("bairro: ",bairro)
print ("cidade: ",cidade)
print ("estado: ",estado)
print ("telefone ",telefone)
