Algoritmo "exercicio5"
Var
nomecliente : caracter
nomeproduto : caracter
preco : real
quantidade : inteiro
total : real
Inicio
escreva ("digite nome cliente: ")
leia (nomecliente)
escreva ("digite nome produto: ")
leia (nomeproduto)
escreva ("digite preço R$: ")
leia (preco)
escreva ("digite quantidade: ")
leia (quantidade)
total := quantidade * preco
escreva ("total a pagar R$: ", total)
Fimalgoritmo