Algoritmo "exercicio2"
Var
nome : caracter
endereco : caracter
bairro : caracter
cidade : caracter
estado : caracter
telefone : inteiro
Inicio
escreva ("Digite seu nome: ")
leia (nome)
escreva ("Digite seu endereco: ")
leia (endereco)
escreva ("Digite seu bairro: ")
leia (bairro)
escreva ("Digite sua cidade: ")
leia (cidade)
escreva ("Digite seu estado: ")
leia (estado)
escreva ("Digite seu telefone: ")
leia (telefone)
Fimalgoritmo